//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.Incidencias = new HashSet<Incidencia>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> hora_dia_llegadaEstimada { get; set; }
        public System.DateTime hora_dia_abierto { get; set; }
        public double precio_servicio { get; set; }
        public double nota_faena { get; set; }
        public System.DateTime travel_ini { get; set; }
        public System.DateTime travel_fin { get; set; }
        public byte[] firma_dig { get; set; }
        public int id_cliente { get; set; }
        public int id_paquete { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Paquete Paquete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidencia> Incidencias { get; set; }
    }
}
