//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.Paquetes = new HashSet<Paquete>();
            this.Trabajadors = new HashSet<Trabajador>();
        }
    
        public int id { get; set; }
        public System.DateTime data_recepcion { get; set; }
        public Nullable<System.DateTime> data_retorno { get; set; }
        public int id_paquete { get; set; }
        public int id_trabajador { get; set; }
    
        public virtual Paquete Paquete { get; set; }
        public virtual Trabajador Trabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paquete> Paquetes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trabajador> Trabajadors { get; set; }
    }
}
