//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactesRepositori
{
    using System;
    using System.Collections.Generic;
    
    public partial class email
    {
        public int emailId { get; set; }
        public string email1 { get; set; }
        public string tipus { get; set; }
        public Nullable<int> contacteId { get; set; }
    
        public virtual contacte contacte { get; set; }
    }
}
